Simple example of a multi-workspace build that fails when there are resources
Build failes due to resource:
```
$ cd service && bazel build --sandbox_debug //...:all
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets...
ERROR: /private/var/tmp/_bazel_clint/b53724a1440ea0c7b3240e82ef70f0e9/external/lib/core/BUILD:4:1: error executing shell command: '/bin/bash -c external/bazel_tools/tools/zip/zipper/zipper c bazel-out/darwin-fastbuild/bin/external/lib/core/core-resources.jar @bazel-out/darwin-fastbuild/bin/external/lib/core/core_resources_zipp...' failed (Exit 255) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_clint/b53724a1440ea0c7b3240e82ef70f0e9/sandbox/darwin-sandbox/28/execroot/service && \
  exec env - \
    TMPDIR=/var/folders/3m/vrx61wv966jg1jw_0wfl5nnw0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_clint/b53724a1440ea0c7b3240e82ef70f0e9/sandbox/darwin-sandbox/28/sandbox.sb /var/tmp/_bazel_clint/install/8ee987d32e94b9a7b51ef6034faefef4/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'external/bazel_tools/tools/zip/zipper/zipper c bazel-out/darwin-fastbuild/bin/external/lib/core/core-resources.jar @bazel-out/darwin-fastbuild/bin/external/lib/core/core_resources_zipper_args')
File ../lib/core/resources/foo.txt does not seem to exist.
```